export const refs = {
  body: document.querySelector('body'),
  cardMovie: document.querySelector('.film-gallery__list'),
  modalList: document.querySelector('.modal__desc'),
  modal: document.querySelector('[data-modal-main]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  btnAddToWatched: document.querySelector('.modal__btn--watched'),
  btnAddToQueue: document.querySelector('.modal__btn--queue'),
  btnWatched: document.querySelector('.library__btn--watched'),
  btnQueue: document.querySelector('.library__btn--queue'),
  listLibrary: document.querySelector('.library__list'),
  backdropModal: document.querySelector('.backdrop-modal'),
  modalWindow: document.querySelector('.backdrop-footer'),
  studentsModalBtn: document.querySelector('.students-modal'),
  modalClose: document.querySelector('.team-modal__close-btn'),
  teamList: document.querySelector('.team__list'),
  titleLibrary: document.querySelector('.library__title'),
};
