import './js/header';
import './js/gallery';
import './js/genresSelect';
import './js/pagination';
import './js/gallery';
import './js/modal-main';
// import './js/footer';
import './js/modal-footer';
import './utils/storage';
// import './js/theme';
